apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: account-expiration-controller
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: account-expiration-controller
  name: account-expiration-controller-manager
  namespace: kube-system
secrets:
- name: account-expiration-controller-manager-token-t5pgl
